version: '3.4'
services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  #selenium-chrome
  selenium-chrome:
    restart: always
    image: selenium/node-chrome-debug:latest
    stdin_open: true
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=3240
      - SCREEN_HEIGHT=2160
    depends_on:
      - selenium-hub
  #selenium-firefox
  selenium-firefox:
    restart: always
    image: selenium/node-firefox-debug:latest
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=3240
      - SCREEN_HEIGHT=2160
    depends_on:
      - selenium-hub
