apiVersion: batch/v1
kind: Job
metadata:
  name: evgrid-test-002
spec:
  # ttlSecondsAfterFinished: __AUTOTESTMATE_TTLSECONDSAFTERFINISHED__ # seconds
  template:
    metadata:
      labels:
        app: evgrid-test
    spec:
      containers:
        - name: evgrid-test
          image: aacacr.azurecr.io/evgrid-test:0.0.1
          # resources:
          #   requests:
          #     cpu: "__AUTOTESTMATE_REQUESTS_CPU__"
          #     memory: "__AUTOTESTMATE_REQUESTS_MEMORY__"
          #   limits:
          #     cpu: "__AUTOTESTMATE_LIMITS_CPU__"
          #     memory: "__AUTOTESTMATE_LIMITS_MEMORY__"
          imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 6 # default 6, 0 to no restart
  completions: 1000
  parallelism: 10
