kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1
metadata: 
  name: evhub-test-hpa 
spec: 
  minReplicas: 1 
  maxReplicas: 10 
  scaleTargetRef: 
    apiVersion: app/v1 
    kind: Deployment
    name: evhub-test 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 60