apiVersion: batch/v1
kind: Job
metadata:
  name: evhub-test-001
spec:
  # ttlSecondsAfterFinished: __AUTOTESTMATE_TTLSECONDSAFTERFINISHED__ # seconds
  template:
    metadata:
      labels:
        app: evhub-test
    spec:
      containers:
        - name: evhub-test
          image: aacacr.azurecr.io/evhub-test:latest
          # resources:
          #   requests:
          #     cpu: 200m
          #     memory: 1Mi
          #   limits:
          #     cpu: 1
          #     memory: 2Mi
          imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 6 # default 6, 0 to no restart
  completions: 1000
  parallelism: 10
