version: '3'
services:
  database:
    build: .
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - p-db-data:/data/db
    ports:
      - '32143:27017'
volumes:
  p-db-data:
